DELETE FROM [Bonava-Test].[dbo].[Real Estate$Company Information$437dbf0e-84ff-417a-965d-ed2bb9650972];

-- Company Information
-- Base Table
INSERT INTO [Bonava-Test].[dbo].[Real Estate$Company Information$437dbf0e-84ff-417a-965d-ed2bb9650972]
(
	[Primary Key],
	[Name],
	[Name 2],
	[Address],
	[Address 2],
	[City],
	[Phone No_],
	[Phone No_ 2],
	[Telex No_],
	[Fax No_],
	[Giro No_],
	[Bank Name],
	[Bank Branch No_],
	[Bank Account No_],
	[Payment Routing No_],
	[Customs Permit No_],
	[Customs Permit Date],
	[VAT Registration No_],
	[Registration No_],
	[Telex Answer Back],
	[Ship-to Name],
	[Ship-to Name 2],
	[Ship-to Address],
	[Ship-to Address 2],
	[Ship-to City],
	[Ship-to Contact],
	[Location Code],
	[Post Code],
	[County],
	[Ship-to Post Code],
	[Ship-to County],
	[E-Mail],[Home Page],
	[Country_Region Code],
	[Ship-to Country_Region Code],
	[IBAN],[SWIFT Code],
	[Industrial Classification],
	[IC Partner Code],
	[IC Inbox Type],
	[IC Inbox Details],
	[System Indicator],
	[Custom System Indicator Text],
	[System Indicator Style],
	[Responsibility Center],
	[Check-Avail_ Period Calc_],
	[Check-Avail_ Time Bucket],
	[Base Calendar Code],
	[Cal_ Convergence Time Frame],
	[Director No_],
	[Director Name],
	[Accountant Name],
	[Accountant No_],
	[OGRN Code],
	[OKPO Code],
	[OKONX Code],
	[OKOPF Code],
	[OKFS Code],
	[Full Name],
	[Bank BIC],
	[Region Code],
	[Populated Locality],
	[Street],
	[House],
	[Building],
	[Apartment],
	[KPP Code],
	[Status],
	[Registration Date],
	[Principal Activity],
	[OKOGU Code],
	[OKATO Code],
	[OKVED Code],
	[HR Manager No_],
	[Taxation Body No_],
	[Taxation Body Name],
	[Taxation Body District],
	[Taxation Body Address],
	[Taxation Body Address 2],
	[Taxation Body Post Code],
	[Taxation Body Phone No_],
	[Pension Fund Registration No_],
	[Medical Fund Registration No_],
	[Social Insurance Fund Agency],
	[Social Insurance Code],
	[Tax Bearer Category],
	[Tax Bearer Category Code],
	[Pension Fund Registration Name],
	[Bank City],
	[Bank Corresp_ Account No_],
	[Company Status],
	[Administrative Region],
	[Primary Activity],
	[Form of Ownership],
	[Separated Org_ Unit],
	[Region Name],
	[Municipal District],
	[FSI Registration No_],
	[Reg_ Country_Region Code],
	[Property Locat_ KPP Code],
	[Stat_ Acc_ Sert_ - Series],
	[Stat_ Acc_ Sert_ - No_],
	[Stat_ Acc_ Sert_ - Issue Date],
	[Stat_ Acc_ Sert_ - Issue State],
	[Stat_ Acc_ Sert_ - Issue Code],
	[Representative Organization],
	[Representative First Name],
	[Representative Middle Name],
	[Representative Last Name],
	[Representative Document],
	[Import Curr_ Exch_ Rates],
	[Import Conflict Resolution]
)
SELECT 
	[Primary Key],
	[Name],
	[Name 2],
	[Address],
	[Address 2],
	[City],
	[Phone No_],
	[Phone No_ 2],
	[Telex No_],
	[Fax No_],
	[Giro No_],
	[Bank Name],
	[Bank Branch No_],
	[Bank Account No_],
	[Payment Routing No_],
	[Customs Permit No_],
	[Customs Permit Date],
	[VAT Registration No_],
	[Registration No_],
	[Telex Answer Back],
	[Ship-to Name],
	[Ship-to Name 2],
	[Ship-to Address],
	[Ship-to Address 2],
	[Ship-to City],
	[Ship-to Contact],
	[Location Code],
	[Post Code],
	[County],
	[Ship-to Post Code],
	[Ship-to County],
	[E-Mail],[Home Page],
	[Country_Region Code],
	[Ship-to Country_Region Code],
	[IBAN],[SWIFT Code],
	[Industrial Classification],
	[IC Partner Code],
	[IC Inbox Type],
	[IC Inbox Details],
	[System Indicator],
	[Custom System Indicator Text],
	[System Indicator Style],
	[Responsibility Center],
	[Check-Avail_ Period Calc_],
	[Check-Avail_ Time Bucket],
	[Base Calendar Code],
	[Cal_ Convergence Time Frame],
	[Director No_],
	[Director Name],
	[Accountant Name],
	[Accountant No_],
	[OGRN Code],
	[OKPO Code],
	[OKONX Code],
	[OKOPF Code],
	[OKFS Code],
	[Full Name],
	[Bank BIC],
	[Region Code],
	[Populated Locality],
	[Street],
	[House],
	[Building],
	[Apartment],
	[KPP Code],
	[Status],
	[Registration Date],
	[Principal Activity],
	[OKOGU Code],
	[OKATO Code],
	[OKVED Code],
	[HR Manager No_],
	[Taxation Body No_],
	[Taxation Body Name],
	[Taxation Body District],
	[Taxation Body Address],
	[Taxation Body Address 2],
	[Taxation Body Post Code],
	[Taxation Body Phone No_],
	[Pension Fund Registration No_],
	[Medical Fund Registration No_],
	[Social Insurance Fund Agency],
	[Social Insurance Code],
	[Tax Bearer Category],
	[Tax Bearer Category Code],
	[Pension Fund Registration Name],
	[Bank City],
	[Bank Corresp_ Account No_],
	[Company Status],
	[Administrative Region],
	[Primary Activity],
	[Form of Ownership],
	[Separated Org_ Unit],
	[Region Name],
	[Municipal District],
	[FSI Registration No_],
	[Reg_ Country_Region Code],
	[Property Locat_ KPP Code],
	[Stat_ Acc_ Sert_ - Series],
	[Stat_ Acc_ Sert_ - No_],
	[Stat_ Acc_ Sert_ - Issue Date],
	[Stat_ Acc_ Sert_ - Issue State],
	[Stat_ Acc_ Sert_ - Issue Code],
	[Representative Organization],
	[Representative First Name],
	[Representative Middle Name],
	[Representative Last Name],
	[Representative Document],
	[Import Curr_ Exch_ Rates],
	[Import Conflict Resolution]
FROM [VM-PRO-SQL007\NAV].[NAV_for_Developers].[dbo].[NCC Real Estate$Company Information];


DELETE FROM [Bonava-Test].[dbo].[Real Estate$Company Information$2944687f-9cf8-4134-a24c-e21fb70a8b1a];

-- Table Extension
INSERT INTO [Bonava-Test].[dbo].[Real Estate$Company Information$2944687f-9cf8-4134-a24c-e21fb70a8b1a]
(
	[Primary Key],
	[Company Type],
	[Use RedFlags in Agreements]
)
SELECT
	[Primary Key],
	[Company Type],
	[Use RedFlags in Agreements]
FROM [VM-PRO-SQL007\NAV].[NAV_for_Developers].[dbo].[NCC Real Estate$Company Information];