DELETE FROM [Bonava-Test].[dbo].[Bonava$Vendor Bank Account$437dbf0e-84ff-417a-965d-ed2bb9650972];

--Vendor Bank Account
INSERT INTO [Bonava-Test].[dbo].[Bonava$Vendor Bank Account$437dbf0e-84ff-417a-965d-ed2bb9650972]
(
	[Vendor No_],
	[Code],
	[Name],
	[Name 2],
	[Address],
	[Address 2],
	[City],
	[Post Code],
	[Contact],
	[Phone No_],
	[Telex No_],
	[Bank Branch No_],
	[Transit No_],
	[Currency Code],
	[Country_Region Code],
	[County],
	[Fax No_],
	[Telex Answer Back],
	[Language Code],
	[E-Mail],
	[Home Page],
	[IBAN],
	[SWIFT Code],
	[BIC],
	[Abbr_ City],
	[VAT Registration No_],
	[Personal Account No_],
	[Def_ Payment Purpose],
	[Bank Corresp_ Account No_],
	[Bank Card No_]
)
SELECT
	[Vendor No_],
	[Code],
	[Name],
	[Name 2],
	[Address],
	[Address 2],
	[City],
	[Post Code],
	[Contact],
	[Phone No_],
	[Telex No_],
	[Bank Branch No_],
	[Transit No_],
	[Currency Code],
	[Country_Region Code],
	[County],
	[Fax No_],
	[Telex Answer Back],
	[Language Code],
	[E-Mail],
	[Home Page],
	[IBAN],
	[SWIFT Code],
	[BIC],
	[Abbr_ City],
	[VAT Registration No_],
	[Personal Account No_],
	[Def_ Payment Purpose],
	[Bank Corresp_ Account No_],
	[Bank Card No_]
FROM [VM-PRO-SQL007\NAV].[NAV_for_Developers].[dbo].[Bonava$Vendor Bank Account];